services:
  - type: web
    name: craft-app
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    plan: free
    nodeVersion: 16
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /health
    branch: main 