services:
  - type: web
    name: craft-api
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    plan: free
    nodeVersion: 16
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PYTHON_SERVICE_URL
        value: internal://craft-mcp-service
    autoDeploy: true
    healthCheckPath: /health
    branch: main

  - type: web
    name: craft-mcp-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mcp_server.py
    plan: free
    pythonVersion: 3.9
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: MCP_PORT
        value: 5000
    autoDeploy: true
    healthCheckPath: /health
    branch: main 