services:
  - type: web
    name: craft-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node src/index.js
    runtime: node
    nodeVersion: 16
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /
    branch: main 