name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List repository contents
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Verify Node.js installation
        run: |
          node --version
          npm --version

      - name: Verify package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✓ package.json found"
            echo "Contents:"
            cat package.json
          else
            echo "✗ package.json not found"
            exit 1
          fi

      - name: Install dependencies
        if: success()
        run: npm install
