name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "GitHub Workspace contents:"
          ls -la $GITHUB_WORKSPACE

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './package.json'

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: npm ci

      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: npm test

      - name: Run linting
        working-directory: ${{ github.workspace }}
        run: npm run lint

      - name: Build
        working-directory: ${{ github.workspace }}
        run: npm run build

  # Only run MCP deployment on main branch
  deploy-to-mcp:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to MCP
        run: python deploy_to_mcp.py
        env:
          MCP_API_KEY: ${{ secrets.MCP_API_KEY }}
