name: Python MCP Service

on:
  push:
    branches: 
      - main
      - feature/python-mcp
  pull_request:
    branches: 
      - main

jobs:
  mcp-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mcp
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          MCP_API_KEY: ${{ secrets.MCP_API_KEY }}
          MCP_ENVIRONMENT: test
        run: |
          python -m pytest tests/ -v

      - name: Run linting
        run: |
          python -m flake8 . --max-line-length=88 --extend-ignore=E203
          python -m black . --check --quiet 